[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
service_marketplace = "i6VA27quutNQdauLuZPfHRFCBwXywCEV4JauuswHS2i"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "anchor test"

[program]
service_marketplace = "programs/service_marketplace"

[idl]
out = "target/idl/"
